apiVersion: apps/v1
kind: Deployment
metadata:
  name: storpool-csi-controllerplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: storpool-csi-controllerplugin
  template:
    metadata:
      labels:
        name: storpool-csi-controllerplugin
    spec:
      serviceAccountName: storpool-csi-controller-sa
      containers:
        - name: storpool-csi-plugin
          image: netcho/storpool-csi:0.0.2-3
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: SP_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
          volumeMounts:
            - name: storpool-conf
              mountPath: /etc/storpool.conf
              readOnly: true
            - name: storpool-dir
              mountPath: /usr/lib/storpool
              readOnly: true
            - name: socket-dir
              mountPath: /csi
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--default-fstype=ext4"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: storpool-conf
          hostPath:
            path: /etc/storpool.conf
            type: File
        - name: storpool-dir
          hostPath:
            path: /usr/lib/storpool
            type: Directory
        - name: socket-dir
          emptyDir: {}